---
- name: Create aur_builder user
  user:
    name: aur_builder
    group: wheel
    shell: /sbin/nologin

- name: Setup sudo permissions for aur_builder
  lineinfile:
    path: /etc/sudoers.d/11-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: Check if {{ aur_helper }} package helper is installed
  command: pacman -Qi {{ aur_helper }}
  register: aur_helper_installed
  ignore_errors: yes

- name: Install {{ aur_helper }} AUR package helper
  become: true
  become_user: aur_builder
  aur:
    name: "{{ aur_helper }}"
    use: makepkg
  when: aur_helper_installed.rc != 0

