---
- name: Configure NTP Synchronization and TimeZone
  import_role:
    name: geerlingguy.ntp

- name: Check if NTP synchronization is enabled
  command: timedatectl show -p NTPSynchronized
  register: ntp_working
  ignore_errors: true

- name: Enable NTP Synchronization in timedatectl
  command: timedatectl set-ntp true
  when: ntp_working.stdout == 'NTPSynchronized=no'

- name: Generate adjtime from HW clock
  command: hwclock --systohc
  args:
    creates: /etc/adjtime